### ISSUE TITLE
Rebuild Failing 

### ISSUE THREAD

**Issue by mwweb** [appcelerator/node-ios-device#19]
I am attempting to install vcremote, and it appears to be working fine unit it gets to node-iso-device@0.5.2 install: 'note-gyp rebuild' which results in an Exit status 1.

Node version 6.3.1
NPM version 3.10.3

[npm-debug.txt](https://github.com/appcelerator/node-ios-device/files/389477/npm-debug.txt)

**Comment by cb1kenobi** [comment]
node-ios-device 0.5.2 is pretty old and doesn't support Node 6. Please update to v0.10.1 which does.
