### ISSUE TITLE
Kills Node After About a Day with a Large Number of Devices Attached

### ISSUE THREAD

**Issue by rosesandhello** [appcelerator/node-ios-device#24]
So, I have two MacMini hubs running on El Capitan (10.11.4) that have 30-40 iDevices attached each.

After roughly a day of running, my program fails silently. Because it is a daemon, it's immediately restarted but fails again and again at the place I start tracking iDevices. Looking through the system logs, it seems tied to this module. 

Also worth noting is that this program runs without fail on identical hubs with only Androids attached.

Any insight is greatly appreciated. Absurdly long crash dump is attached.
[crashdump.txt](https://github.com/appcelerator/node-ios-device/files/453656/crashdump.txt)

**Comment by cb1kenobi** [comment]
Wow. OK. The most amount of devices I've ever tested I think was 3.

I don't think you're using the latest version. I see references to Boost::shared_mutex which was removed.

Also, Thread 13 that crashed references `CFNumberGetValue()` which was also removed a couple weeks ago: https://github.com/appcelerator/node-ios-device/commit/757cbefd4d7bcaf812b0ae0d5d638135f8fce390.

Make sure you using the latest node-ios-device@0.11.2.

**Comment by cb1kenobi** [comment]
No new reports in the past 2+ years. I'm going to assume the latest version resolves the issue.
