### ISSUE TITLE
.trackDevices doesn't seem to catch any events

### ISSUE THREAD

**Issue by Ronin11** [appcelerator/node-ios-device#28]
I've tried everything I can think of to get trackDevices to work and I'm at a loss. The devices function works fine tells me the status of the phone when called, but for some reason trackDevices doesn't catch any 'device' or 'error' events. Should I be listening for other events? My code is just the example in the README. 
Mac version: 10.12.4
Node version: 7.2.1
IOS Device: iPhone 6s

https://github.com/appcelerator/node-ios-device/issues/14
I saw that you're using the iTunes library to talk to the devices, are you supplying your own, or just using the one that exists on the machine?

Thanks for the help.

**Comment by cb1kenobi** [comment]
I just tested it on my Mac (10.12.4) with Node 7.9.0 and the latest node-ios-device@1.3.1 and it works just fine. I just ran the test: https://github.com/appcelerator/node-ios-device/blob/master/test/test-track-devices.js. The event is `devices`, not `device`.

node-ios-device does use MobileDevice.framework.

**Comment by Ronin11** [comment]
Ah, in your example it has `device` not `devices`. It seems to work fine now.

Thanks!

**Comment by cb1kenobi** [comment]
Nice!
