### ISSUE TITLE
1.4.0 missing bundled dependency node-pre-gyp's dependencies

### ISSUE THREAD

**Issue by dead-horse** [appcelerator/node-ios-device#35]
in 1.3.3, the package publish to npm contains node-pre-gyp(bundled dependency)'s dependencies, but in 1.4.0, only `node-pre-gyp` is inside, but its dependencies are missing. it will install fail in some situation because of find unmatched dependencies.

![image](https://user-images.githubusercontent.com/985607/30794562-846aa2aa-a18e-11e7-882d-cb15cd10911e.png)

**Comment by cb1kenobi** [comment]
`node-pre-gyp`'s dependencies are installed along side `node-ios-device` in the `node_modules` directory. This is the default behavior for NPM 4 and newer (and maybe as early as NPM 3).

`node-ios-device@1.4.0` is correct.

It looks like `node-ios-device@1.3.3` may have been published with an older version of NPM where all of `node-pre-gyp`'s dependencies were bundled when they should not have been. `node-ios-device` is published via our CI server, so it's possible NPM was out-of-date at the time 1.3.3 was published.

`node-pre-gyp`s dependencies are resolved when `npm i --production` is run.
