### ISSUE TITLE
Can I convert CFData to Key 

### ISSUE THREAD

**Issue by praveen4554** [appcelerator/node-ios-device#53]
Hi,

  I would like to use RSA keys generate by IOS in node to encrypt the Data from IOS we can send CFData and I would like to convert CFData to Seckey and encrypt a plain text

**Comment by cb1kenobi** [comment]
Sorry, but that functionality is outside the scope of node-ios-device. This library is simply for installing apps on your computer to an iOS device. It doesn't directly do anything with encryption and is completely separate from your app. You will have to look elsewhere. Best of luck!
