### ISSUE TITLE
Crash without error message in the Electron application.

### ISSUE THREAD

**Issue by zcmgyu** [appcelerator/node-ios-device#58]
After about 1 week of debugging to figure out the cause of the application closing itself without any error message, I discovered that the main cause of crashing is from the node-ios-device library.
Everything works normally, but after about 1 hour, a crash occurs. What I think is strange is that a crash occurs even `iosDevice.watch()` was not called. Or just by importing the node-ios-devices library can a crash occur.

Sometimes, I got this message after crashing as well.

`[21194:0607/225605.295914:FATAL:message_pump_kqueue.cc(387)] : Bad file descriptor (9)`

This is a great library, I would appreciate it if you could show me how to fix this problem. (bow)

Reproduction: https://github.com/zcmgyu/crash-electron-node-ios-device/blob/master/main.js#L22-L28

```
const handle = iosDevice.watch();
  handle.on('change', devices => {
    console.log('Connected devices:', devices);
  });
  handle.on('error', console.error);

  iosDevice.on('log', msg => console.log(msg));
```

This is logs output from `iosDevice.on('log')`

```
$ electron .
Creating device list with 1 devices
Connected devices: [
  {
    udid: 'XXXX',
    interfaces: [ 'Wi-Fi' ],
    name: 'ZC X',
    buildVersion: '17F75',
    cpuArchitecture: 'arm64',
    deviceClass: 'iPhone',
    deviceColor: 'Black',
    hardwareModel: 'D22AP',
    modelNumber: 'MQAY2',
    productType: 'iPhone10,3',
    productVersion: '13.5',
    serialNumber: 'FK1VVTGLJCLL',
    trustedHostAttached: false
  }
]
Adding listener
Creating device list with 1 devices
Resetting timer due to new device notification
Device XXXX disconnected via Wi-Fi
Connected devices: []
Creating device list with 0 devices
Dispatching device changes to 1 listener (thread 2978043419396287625)
Resetting timer due to new device notification
Device XXXX connected via Wi-Fi
Getting device info for XXXX
Connecting to device: XXXX
Pairing device: XXXX
Validating device pairing
Starting session: XXXX
Stopping session: XXXX
Disconnecting from device: XXXX
Connected devices: [
  {
    udid: 'XXXX',
    interfaces: [ 'Wi-Fi' ],
    name: 'ZC X',
    buildVersion: '17F75',
    cpuArchitecture: 'arm64',
    deviceClass: 'iPhone',
    deviceColor: 'Black',
    hardwareModel: 'D22AP',
    modelNumber: 'MQAY2',
    productType: 'iPhone10,3',
    productVersion: '13.5',
    serialNumber: 'FK1VVTGLJCLL',
    trustedHostAttached: false
  }
]
Creating device list with 1 devices
Dispatching device changes to 1 listener (thread 2978043419396287625)
Resetting timer due to new device notification
Device XXXX disconnected via Wi-Fi
Connected devices: []
✨  Done in 225.28s.
```

> node-ios-device: 2.0.2
> electron: 9.0.2
> node: 14.3.0

**Comment by cb1kenobi** [comment]
Thank you for bringing this issue to my attention. I have not yet tested it against Node 14, so there could be some issue with the latest libuv or something. I'll take a peek.

**Comment by zcmgyu** [comment]
Hi @cb1kenobi, I tried with version 1.7.1 that crash does not occur anymore, but it makes for 4 instances of Electron application.
https://github.com/zcmgyu/crash-electron-node-ios-device/tree/1.7.1

Otherwise, I tested `node-ios-device` with Node 14 and I don't think this issue related to Node 14. It just occurs when used in the Electron project.

**Comment by cb1kenobi** [comment]
@zcmgyu OK, I did a build with Electron compatibility and published v2.1.0. Can you please give it a try? Thanks!

**Comment by zcmgyu** [comment]
OMG. I will try it and will response ASAP

**Comment by zcmgyu** [comment]
Hi, @cb1kenobi I've checked it. After 10989.90s application crashes again.

**Comment by zcmgyu** [comment]
Currently, 1.7.1 worked for me, I've made a ticket on Electron already. Thanks for your support.

**Comment by cb1kenobi** [comment]
@zcmgyu I thought you might be interested to hear that I just release node-ios-device 3.0.0. I found a segfault and fixed it. I'm not convinced it has anything to do with the bad file descriptor error you ran into, but figured you'd want to know. v3 also has a few other breaking changes that probably won't affect  you. Here's the release notes: https://github.com/appcelerator/node-ios-device/releases/tag/v3.0.0. Cheers!

**Comment by zcmgyu** [comment]
@cb1kenobi OMG, you are awesome. I will check it on business day.

**Comment by zcmgyu** [comment]
Hi @cb1kenobi. I've been testing the Electron application crashing with a 3.0.0 version for a couple of days. It's still working without crashing. Thanks for your hard work. <3
I will close this ticket.

**Comment by cb1kenobi** [comment]
@zcmgyu This is the best news I've heard all day! Thank you for your assistance and best of luck with your project! Cheers!
